# -----------------application:configs--------------------------
# 1.spring configs (db...)
# 2.app configs
# 3.log configs
# 4.common configs
# ---------------------------------------------------------------

server:
  port: 8666      #以内嵌容器形式运行时，服务绑定的端口;当服务以war包形式部署在tomcat等容器中时，会忽略server.port配置节点

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #日期序列化格式

# log配置
logging:
  config: classpath:logback.xml

# 远程接口地址
remote.devicestatusurl: http://172.18.8.35:8080/pivs-backend/device-status/update  #更新设备状态接口

websocket:
  server:
    host: 192.168.3.247
    port: 13520
  profiles:
    active: dev

redis:
  host: 192.168.3.247
  port: 6379



